# https://www.mkdocs.org/user-guide/configuration/
# https://squidfunk.github.io/mkdocs-material/

# site
site_name: 上应 Wiki
site_url: https://kite.sunnysab.cn/wiki/
site_description: >-
  这是一个由上海应用技术大学易班工作站、树洞盒子和表白墙共同发起的项目，旨在解答大家的疑问。
site_author: "上应大易班,树洞盒子,表白墙"

# repo
# repo_name: SIT-kite/SIT-wiki
repo_url: https://github.com/SIT-kite/SIT-wiki

copyright: 上应 Wiki, 采用 CC0-1.0 协议授权

theme:
  name: material
  language: zh
  # logo: assets/logo.svg
  # favicon: assets/favicon.svg
  palette:
    - { scheme: default, toggle: { name: 使用暗色主题, icon: material/brightness-4 } }
    - { scheme: slate,   toggle: { name: 使用亮色主题, icon: material/brightness-7 } }
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand

extra:
  social:
    - { name: 上应小风筝 SIT-kite, link: https://github.com/SIT-kite, icon: fontawesome/brands/github }

extra_css:
  - stylesheets/extra.css

# https://squidfunk.github.io/mkdocs-material/setup/extensions/
# https://python-markdown.github.io/extensions/#officially-supported-extensions
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:

  # ---
  # title: title
  # description: description
  # ---
  - meta

  - sane_lists     # https://python-markdown.github.io/extensions/sane_lists/
  - pymdownx.extra # https://facelessuser.github.io/pymdown-extensions/extensions/extra/

  - pymdownx.caret # ^s  ^HTML <sup> (superscript)^  ^^HTML <ins>^^
  - pymdownx.tilde # ~s   ~HTML <sub> (subscript)~   ~~HTML <del>~~
  - pymdownx.mark  # ==HTML <mark>==

  # ???  "HTML<details>"
  # ???+ "HTML<details open>"
  - pymdownx.details

  - pymdownx.highlight
  - pymdownx.tasklist: { custom_checkbox: true }

strict: true
use_directory_urls: true
