# https://www.mkdocs.org/user-guide/configuration/
# https://squidfunk.github.io/mkdocs-material/

# site
site_name: 上应 Wiki
site_url: https://kite.sunnysab.cn/wiki/
copyright: 上应 Wiki, 采用 CC0-1.0 协议授权
site_author: "上应大易班,树洞盒子,表白墙"
site_description: >-
  这是一个由上海应用技术大学易班工作站、树洞盒子和表白墙共同发起的项目，
  旨在解答大家的疑问。

# repo
repo_name: 上应 Wiki @ GitHub
repo_url: https://github.com/SIT-kite/SIT-wiki

# ------------------------------------------------------------------------------

theme:

  name: material
  language: zh
  # font: false
  # logo: assets/logo.svg
  # favicon: assets/favicon.svg

  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle: { name: 切换至暗色主题, icon: material/brightness-4 }
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle: { name: 切换至亮色主题, icon: material/brightness-7 }

  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.indexes

# ------------------------------------------------------------------------------

extra:
  social:
    - name: 上应小风筝 SIT-kite
      link: https://github.com/SIT-kite
      icon: fontawesome/brands/github

# https://www.mkdocs.org/user-guide/configuration/#extra_css
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/baidu-stats.js

# https://www.mkdocs.org/user-guide/configuration/#use_directory_urls
use_directory_urls: true

# https://www.mkdocs.org/user-guide/configuration/#strict
strict: true

# ------------------------------------------------------------------------------

# https://squidfunk.github.io/mkdocs-material/setup/extensions/
# https://python-markdown.github.io/extensions/#officially-supported-extensions
# https://facelessuser.github.io/pymdown-extensions/

markdown_extensions:

  # ---
  # title: title
  # description: description
  # ---
  - meta

  - sane_lists     # https://python-markdown.github.io/extensions/sane_lists/
  - pymdownx.extra # https://facelessuser.github.io/pymdown-extensions/extensions/extra/

  - pymdownx.caret # ^s    ^HTML <sup> (superscript)^    ^^HTML <ins>^^
  - pymdownx.tilde # ~s    ~HTML <sub>   (subscript)~    ~~HTML <del>~~
  - pymdownx.mark  # ==HTML <mark>==

  # ???  "HTML<details>"
  # ???+ "HTML<details open>"
  - pymdownx.details

  # ``` yaml
  # code: highlight
  # ```
  - pymdownx.highlight

  # - [ ] task
  # - [x] list
  - pymdownx.tasklist: { custom_checkbox: true }

  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - pymdownx.emoji:
      emoji_index:     !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# ------------------------------------------------------------------------------

# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
# https://www.mkdocs.org/user-guide/configuration/#nav

nav:

  - 主页:
    - index.md
    - contribute.md
    - about.md

  - 奉贤校区:
    - fengxian/index.md
    - fengxian/water.md
    - 食堂菜单:
      - fengxian/canteen-menu/index.md
      - fengxian/canteen-menu/canteen-1.md
      - fengxian/canteen-menu/canteen-2.md
      - fengxian/canteen-menu/canteen-3.md

  - 上应小风筝:
    - kite-app/about.md
    - kite-app/changelog.md
    - kite-app/features.md
    - kite-app/todo.md
    - kite-app/why-do-we-migrate.md
