# This workflow will install Python dependencies, build wiki pages and deploy.
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish Wiki

on:
  push:         { branches: [ master ] }
  pull_request: { branches: [ master ] }

jobs:
  build:

    runs-on: ubuntu-latest
    strategy: { matrix: { python-version: ["3.10"] } }

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }} 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mkdocs-material
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build wiki pages
      run: |
        mkdocs build

    - name: Copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_SECRET }}
        source: "./site/*"
        target: "/var/kite/SIT-wiki/site/"
        strip_components: 1

    - uses: technote-space/workflow-conclusion-action@v2

    - name: 💡 Telegram Notification
      if: env.WORKFLOW_CONCLUSION == 'failure' 
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.BOT_TOKEN }}
        chatId: ${{ secrets.CHAT_ID }}
        jobStatus: ${{ env.WORKFLOW_CONCLUSION }} 
  
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with: { length: 7 }

    - name: 🚀 Telegram Bot Message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.BOT_TOKEN }}
        message: |
          🎉 Wiki Update!
          
          Author: ${{ github.actor }}
          
          Message: ${{ github.event.head_commit.message }}
          
          See changes: https://github.com/${{ github.repository }}/commit/${{ env.SHA }}
